definitions:
  Drink:
    properties:
      description:
        type: string
      id:
        type: integer
      name:
        description: |-
          todo Add fields: Name, Price, Description with suitable types
          todo json attributes need to be snakecase, i.e. name, created_at, my_variable, ..
        type: string
      price:
        type: number
    type: object
  Order:
    properties:
      amount:
        type: integer
      drink_id:
        description: foreign key
        type: integer
    type: object
info:
  contact:
    name: Lea Treml
  description: This system enables drink orders and should not be used for the forbidden
    Hungover Games.
  title: Order System
paths:
  /api/menu:
    get:
      description: Returns the menu of all drinks
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/Drink'
            type: array
      tags:
      - Menu
  /api/order:
    post:
      consumes:
      - application/json
      description: Adds an order to the db
      parameters:
      - description: Order
        in: body
        name: b
        required: true
        schema:
          $ref: '#/definitions/Order'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
      tags:
      - Order
  /api/order/all:
    get:
      description: Return all the placed orders
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/Order'
            type: array
      tags:
      - AllOrders
  /api/order/totalled:
    get:
      description: Return how many times each drink was purchased
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/Order'
            type: array
      tags:
      - GetTotalOrders
swagger: "2.0"
